# Generated by Django 5.2 on 2025-09-20 08:22

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0017_remove_order_delivery_order_delivery'),
        ('users', '0003_user_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_address_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept', models.BooleanField(default=False)),
                ('night_mode_availability', models.BooleanField(default=False)),
                ('delivery_notifications', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preference', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('nin_url', models.URLField(null=True)),
                ('proof_of_address', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('poa_url', models.URLField(null=True)),
                ('drivers_licence', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('drivers_licence_url', models.URLField(null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=250, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('pick_address', models.CharField(blank=True, max_length=500, null=True)),
                ('drop_address', models.CharField(blank=True, max_length=500, null=True)),
                ('alternative_drop_address', models.CharField(blank=True, max_length=500, null=True)),
                ('alternative_receipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('package_type', models.CharField(blank=True, choices=[('Document', 'Document'), ('Parcel', 'Parcel'), ('Envelope', 'Envelope'), ('Food', 'Food'), ('Fragile', 'Fragile'), ('Electronics', 'Electronics'), ('Box', 'Box'), ('Crate', 'Crate'), ('Pallet', 'Pallet'), ('Other', 'Other')], max_length=250, null=True)),
                ('package_description', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('rider_preference', models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Vehicle', 'Vehicle')], max_length=250, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_package', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logistics.packagedelivery')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_parcel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('duration_minutes', models.IntegerField(null=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('courier_type', models.CharField(blank=True, max_length=250, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('delivery_type', models.CharField(blank=True, choices=[('Order', 'Order'), ('Package', 'Package')], max_length=250, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='stores.order')),
                ('package_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_delivery', to='logistics.packagedelivery')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ride', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_shipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(choices=[('morning', 'Morning (8AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 5PM)'), ('evening', 'Evening (5PM - 8PM)')], default='morning', max_length=20)),
                ('delivery_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='logistics.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_rate_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('carrier_name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rates', to='logistics.address')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='logistics.parcel')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_rates', to='logistics.address')),
            ],
            options={
                'ordering': ['total'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.shippingrate'),
        ),
    ]
