# Generated by Django 5.2 on 2025-08-16 20:45

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalRiders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept', models.BooleanField(default=False)),
                ('night_mode_availability', models.BooleanField(default=False)),
                ('delivery_notifications', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preference', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('nin_url', models.URLField(null=True)),
                ('proof_of_address', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('poa_url', models.URLField(null=True)),
                ('drivers_licence', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('drivers_licence_url', models.URLField(null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=250, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('duration_minutes', models.IntegerField(null=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('courier_type', models.CharField(blank=True, max_length=250, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='stores.order')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
