# Generated by Django 5.2 on 2025-07-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dropoff_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dropoff_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('duration_minutes', models.IntegerField(null=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
