# Generated by Django 5.2 on 2025-10-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_validateaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='validateaddress',
            name='address_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
