# Generated by Django 5.2 on 2025-08-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_address_parcel_shipment_shipmenttracking_and_more'),
        ('stores', '0004_store_city_store_country_store_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='stores.store'),
        ),
    ]
