# Generated by Django 5.2 on 2025-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_lng',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_lng',
        ),
        migrations.AddField(
            model_name='ride',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
