# Generated by Django 5.2 on 2025-07-28 15:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_ride_dropoff_lat_remove_ride_dropoff_lng_and_more'),
        ('users', '0013_rename_is_online_riderprofile_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept', models.BooleanField(default=False)),
                ('night_mode_availability', models.BooleanField(default=False)),
                ('delivery_notifications', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('proof_of_address', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('drivers_licence', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('vehicle_type', models.CharField(blank=True, max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile')),
            ],
        ),
    ]
