# Generated by Django 5.2 on 2025-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_address_options_remove_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='length',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='value',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='width',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='carrier_code',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='transit_time',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='terminal_rate_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
