# Generated by Django 5.2 on 2025-09-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_parcel_currency_remove_parcel_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='pickup_time',
        ),
    ]
