# Generated by Django 5.2 on 2025-10-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_validateaddress_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validateaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
