# Generated by Django 5.2 on 2025-07-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_ride_rider_bankdetail_deliverypreference_kyc'),
        ('stores', '0082_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.order'),
        ),
    ]
