# Generated by Django 5.2 on 2025-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_validateaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateaddress',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
