# Generated by Django 5.2 on 2025-09-09 15:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_shippingrate_currency_and_more'),
        ('users', '0002_riderprofile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('pickup_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pickups/')),
                ('pickup_photo_url', models.URLField(blank=True, null=True)),
                ('pick_address', models.CharField(blank=True, max_length=500, null=True)),
                ('drop_address', models.CharField(blank=True, max_length=500, null=True)),
                ('alternative_drop_address', models.CharField(blank=True, max_length=500, null=True)),
                ('alternative_receipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_signature', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signatures/')),
                ('package_type', models.CharField(blank=True, choices=[('Document', 'Document'), ('Parcel', 'Parcel'), ('Envelope', 'Envelope'), ('Food', 'Food'), ('Fragile', 'Fragile'), ('Electronics', 'Electronics'), ('Box', 'Box'), ('Crate', 'Crate'), ('Pallet', 'Pallet'), ('Other', 'Other')], max_length=250, null=True)),
                ('package_description', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_preference', models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Vehicle', 'Vehicle')], max_length=250, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='users.riderprofile')),
            ],
        ),
    ]
