# Generated by Django 5.2 on 2025-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_ride_accepted_ride_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='courier_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
