# Generated by Django 5.2 on 2025-09-09 15:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_packagedelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedelivery',
            old_name='pickup_photo',
            new_name='pickup_photo1',
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='pickup_photo12',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pickups/'),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='pickup_photo_url2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
