# Generated by Django 5.2 on 2025-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_validateaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateaddress',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
