# Generated by Django 5.2 on 2025-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_ride_courier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='plate_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
