# Generated by Django 5.2 on 2025-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_validateaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='terminal_shipment_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_from',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_to',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
