# Generated by Django 5.2 on 2025-09-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_rename_pickup_photo_packagedelivery_pickup_photo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedelivery',
            old_name='pickup_photo12',
            new_name='pickup_photo2',
        ),
    ]
