# Generated by Django 5.2 on 2025-07-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_kyc_plate_number_kyc_vehicle_color'),
        ('users', '0014_remove_riderprofile_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='users.riderprofile'),
        ),
        migrations.AlterField(
            model_name='deliverypreference',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preference', to='users.riderprofile'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to='users.riderprofile'),
        ),
    ]
