# Generated by Django 5.2 on 2025-09-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_rename_pickup_photo12_packagedelivery_pickup_photo2'),
        ('users', '0002_riderprofile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedelivery',
            name='recipient_signature',
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='users.riderprofile'),
        ),
    ]
