# Generated by Django 5.2 on 2025-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_bankdetail_rider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='nin_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='poa_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='drivers_licence',
            field=models.URLField(null=True),
        ),
    ]
