# Generated by Django 5.2 on 2025-10-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_shipment_current_location_and_more'),
        ('stores', '0021_delivery_request_token_delivery_service_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='order_id',
            new_name='external_order_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.order'),
        ),
    ]
