# Generated by Django 5.2 on 2025-07-28 20:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_kyc_nin_url_kyc_poa_url_alter_kyc_drivers_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='drivers_licence_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='drivers_licence',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp'),
        ),
    ]
