# Generated by Django 5.2 on 2025-11-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_rename_order_id_shipment_external_order_id_and_more'),
        ('stores', '0022_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='stores.order'),
        ),
    ]
