# Generated by Django 5.2 on 2025-07-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_kyc_drivers_licence_url_alter_kyc_drivers_licence'),
        ('stores', '0084_order_ride_accepted_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='stores.order'),
        ),
    ]
