# Generated by Django 5.2 on 2025-11-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_shipment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
