# Generated by Django 5.2 on 2025-09-11 11:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_packagedelivery_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedelivery',
            name='pickup_photo1',
        ),
        migrations.RemoveField(
            model_name='packagedelivery',
            name='pickup_photo2',
        ),
        migrations.RemoveField(
            model_name='packagedelivery',
            name='pickup_photo_url',
        ),
        migrations.RemoveField(
            model_name='packagedelivery',
            name='pickup_photo_url2',
        ),
        migrations.CreateModel(
            name='DeliveryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logistics.packagedelivery')),
            ],
        ),
    ]
