# Generated by Django 5.2 on 2025-11-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_ride_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='package_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='logistics.packagedelivery'),
        ),
    ]
