# Generated by Django 5.2 on 2025-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_ride_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
