# Generated by Django 5.2 on 2025-11-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_ride_package_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='package_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_ride', to='logistics.packagedelivery'),
        ),
    ]
