# Generated by Django 5.2 on 2025-09-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_ride_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('Order', 'Order'), ('Package', 'Package')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='package_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
