# Generated by Django 5.2 on 2025-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_ride_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
