# Generated by Django 5.2 on 2025-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_ride_out_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
