# Generated by Django 5.2 on 2025-09-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_ride_delivery_type_ride_package_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
