# Generated by Django 5.2 on 2025-09-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_packagedelivery_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='package_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.packagedelivery'),
        ),
    ]
