# Generated by Django 5.2 on 2025-09-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_ride_package_delivery'),
        ('users', '0002_riderprofile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedelivery',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='packagedelivery',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='package_delivery',
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_delivery', to='logistics.ride'),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_package', to='users.userprofile'),
        ),
    ]
