# Generated by Django 5.2 on 2025-09-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_remove_packagedelivery_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedelivery',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='package_sender',
        ),
        migrations.AddField(
            model_name='ride',
            name='package_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_delivery', to='logistics.packagedelivery'),
        ),
    ]
