# Generated by Django 5.2 on 2025-09-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_remove_packagedelivery_ride_and_more'),
        ('stores', '0017_remove_order_delivery_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='stores.order'),
        ),
    ]
