# Generated by Django 5.2 on 2025-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_alter_ride_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
