# Generated by Django 5.2 on 2025-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_packagedelivery_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
