# Generated by Django 5.2 on 2025-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
