# Generated by Django 5.2 on 2025-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='successful_referrals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
