# Generated by Django 5.2 on 2025-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_successful_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_earnings',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
