# Generated by Django 5.2 on 2025-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='duration_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
