# Generated by Django 5.2 on 2025-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_riderprofile_created_at_riderprofile_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
