# Generated by Django 5.2 on 2025-07-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_riderprofile_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='is_online',
            new_name='online',
        ),
    ]
