# Generated by Django 5.2 on 2025-07-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_is_online_riderprofile_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='fare_amount',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_type',
        ),
    ]
