# Generated by Django 5.2 on 2025-08-04 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_riderprofile_address_riderprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
