# Generated by Django 5.2 on 2025-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('card', 'Credit/Debit Card')], max_length=20, null=True)),
                ('provider', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('fund-wallet', 'Fund-Wallet'), ('normal-payment', 'Normal-Payment')], max_length=250, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('card', 'Credit/Debit Card')], max_length=20, null=True)),
                ('payment_provider', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
