# Generated by Django 5.2 on 2025-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_processor_payment_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('fund-wallet', 'Fund-Wallet'), ('normal-payment', 'Normal-Payment')], max_length=250, null=True),
        ),
    ]
