# Generated by Django 5.2 on 2025-08-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('stores', '0005_alter_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='body',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.order'),
        ),
    ]
