# Generated by Django 5.2 on 2025-06-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0033_delivery_alternative_email_delivery_alternative_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatbox')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chatbox',
            index=models.Index(fields=['sender'], name='chat_chatbo_sender__63f9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbox',
            index=models.Index(fields=['receiver'], name='chat_chatbo_receive_4172a8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbox',
            index=models.Index(fields=['product'], name='chat_chatbo_product_c4acb8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbox',
            index=models.Index(fields=['created_at'], name='chat_chatbo_created_4ae536_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chatbox'], name='chat_messag_chatbox_861cec_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='chat_messag_receive_b6ffa6_idx'),
        ),
    ]
