# Generated by Django 5.2 on 2025-08-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatbox_product_remove_chatbox_receiver_and_more'),
        ('stores', '0003_auto_20250809_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='stores.store'),
        ),
    ]
