# Generated by Django 5.2 on 2025-08-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_receiver_message_is_sender_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
