# Generated by Django 5.2 on 2025-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='room_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
