# Generated by Django 5.2 on 2025-08-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_sender__ccacde_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_receive_9e1070_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['room_name'], name='chat_conver_room_na_90054c_idx'),
        ),
    ]
