# Generated by Django 5.2 on 2025-08-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_sender',
        ),
    ]
