# Generated by Django 5.2 on 2025-08-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_message_is_receiver_remove_message_is_sender'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_receive_72f3f5_idx',
            old_name='chat_conver_receive_9e1070_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='receiver',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
