# Generated by Django 5.2 on 2025-08-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_chat_conver_receive_9e1070_idx_chat_conver_receive_72f3f5_idx_and_more'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_receive_9e1070_idx',
            old_name='chat_conver_receive_72f3f5_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='stores.store'),
        ),
    ]
