# Generated by Django 5.2 on 2025-08-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_chat_conver_receive_72f3f5_idx_chat_conver_receive_9e1070_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_receive_0b67f8_idx',
            old_name='chat_messag_receive_b6ffa6_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
