# Generated by Django 5.2 on 2025-08-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_rename_chat_messag_receive_b6ffa6_idx_chat_messag_receive_0b67f8_idx_and_more'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_receive_b6ffa6_idx',
            old_name='chat_messag_receive_0b67f8_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='stores.store'),
        ),
    ]
