# Generated by Django 5.2 on 2025-08-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_rename_chat_messag_receive_0b67f8_idx_chat_messag_receive_b6ffa6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_receive_9e1070_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
    ]
