# Generated by Django 5.2 on 2025-08-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_conversation_receiver'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_chatbox_861cec_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__c4389c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_receive_b6ffa6_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
