# Generated by Django 5.2 on 2025-08-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_remove_message_chat_messag_chatbox_861cec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
