from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
    path('stores/', views.StoreListCreateView.as_view(), name='store-list'),
    path('stores/<str:pk>/', views.StoreDetailView.as_view(), name='store-list'),
    path('dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('orders/', views.OrderListCreateView.as_view(), name='order-list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('delivery/', views.DeliveryDetailsCreateView.as_view(),
         name='delivery_details'),
    path('products/', views.ProductListCreateView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(),
         name='product-detail'),
    path("products/delivery-types/", views.ProductDeliveryTypesView.as_view(), name="product-delivery-types"),
    path('follow/<str:pk>/', views.StoreFollowView.as_view(), name='followstore'),
    path('unfollow/<str:pk>/', views.StoreUnfollowView.as_view(), name='unfollow'),
    path('followers/', views.StoreFollowers.as_view(),
         name='viewstorefollowers'),
    path('following/', views.StoreFollowingView.as_view(), name='following'),
    path('userproducts/', views.UserProductListView.as_view(), name='user-product'),
    path('userproduct/<int:pk>/', views.UserProductDetailView.as_view(),
         name='user-product-detail'),
    path('status/<str:pk>/', views.ProductStatusView.as_view(),
         name='product-status'),
    path('status/', views.StatusView.as_view(), name='status-creation'),
    path('order/<str:pk>/confirm',
         views.ConfirmOrder.as_view(), name='confirm-order'),
    path('order/<str:pk>/mark-for-delivery',
         views.MarkForDeliveryView.as_view(), name='mark-as-delivered'),
    path('order/user/', views.GetUserOrder.as_view(), name='order-history'),
    path('order/<str:pk>/track-order',
         views.TrackOrder.as_view(), name='order_tracking'),
    path('stores/<int:store_id>/reviews/',
         views.ReviewView.as_view(), name='create-review'),
    path('order/<str:pk>/mark-as-delivered',
         views.MarkAsDelivered.as_view(), name='mark-as-delivered'),
    path('verify-order/<str:pk>/',
         views.VerifyOrderView.as_view(), name='verify-order'),
    path('products/more-from-seller/<str:pk>/',
         views.MoreFromSeller.as_view(), name='morefromseller'),
    path('rate-product/<str:pk>',
         views.ProductRatingView.as_view(), name='RateProduct'),
    path('view-store/<str:store_id>/',
         views.ClientViewStore.as_view(), name='view-store'),
    path('get-shipment-rate/', views.GetShippingRate.as_view(), name='shipment-rate'),
    path('confirm-task/<str:task_id>/', views.TaskStatusView.as_view(), name='task-status')
]
