# Generated by Django 5.2 on 2025-06-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletHistory',
            new_name='WalletTransactions',
        ),
    ]
