# Generated by Django 5.2 on 2025-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='type',
            field=models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Item-Purchase', 'Item-Purchase'), ('Account-Funded', 'Account-Funded')], max_length=250, null=True),
        ),
    ]
