# Generated by Django 5.2 on 2025-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransactions_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
