# Generated by Django 5.2 on 2025-06-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_wallethistory_wallettransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='wallet.wallet'),
        ),
    ]
