# Generated by Django 5.2 on 2025-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransactions_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='type',
            field=models.CharField(blank=True, choices=[('Withdrawal', 'Withdrawal'), ('Item-Purchase', 'Item-Purchase')], max_length=250, null=True),
        ),
    ]
