# Generated by Django 5.2 on 2025-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransactions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
