# Generated by Django 5.2 on 2025-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
