# Generated by Django 5.2 on 2025-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reference_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
