# Generated by Django 5.2 on 2025-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='reference_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
