# Generated by Django 5.2 on 2025-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallettransactions_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=250, null=True),
        ),
    ]
