# Generated by Django 5.2 on 2025-06-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='order',
        ),
    ]
