# Generated by Django 5.2 on 2025-06-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_scan_order'),
        ('stores', '0012_orderdispute_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='data',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='user',
        ),
        migrations.AddField(
            model_name='scan',
            name='manual_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='stores.order'),
        ),
        migrations.AddField(
            model_name='scan',
            name='qr_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
