# Generated by Django 5.2 on 2025-08-09 04:18

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_payment_type'),
        ('users', '0016_alter_riderprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_video', models.FileField(blank=True, null=True, upload_to='', verbose_name='videos')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('original_price', models.PositiveBigIntegerField(default=0)),
                ('discounted_price', models.PositiveBigIntegerField(default=0)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], max_length=300, null=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('stock_available', models.IntegerField(blank=True, default=1, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('pickup_available', models.BooleanField(default=True)),
                ('delivery_available', models.BooleanField(default=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('Movbay_Express', 'Movbay_Express'), ('Speedy_Dispatch', 'Speedy_Dispatch'), ('Pickup_Hub', 'Pickup_Hub')], max_length=250, null=True)),
                ('auto_post_to_story', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-verified'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('MovBay_Dispatch', 'MovBay_Dispatch'), ('Speedy_Dispatch', 'Speedy_Dispatch'), ('Pickup_Hub', 'Pickup_Hub')], max_length=250)),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('delivery_address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('alternative_address', models.CharField(blank=True, max_length=250, null=True)),
                ('alternative_name', models.CharField(blank=True, max_length=250, null=True)),
                ('alternative_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NG')),
                ('alternative_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('postal_code', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New Orders'), ('processing', 'Processing'), ('assigned', 'assigned'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=250)),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('ride_accepted', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('otp_secret', models.CharField(blank=True, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.delivery')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.orderdispute')),
                ('orderhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_accepted', models.BooleanField(default=False)),
                ('marked_for_delivery', models.BooleanField(default=False)),
                ('item_picked', models.BooleanField(default=False)),
                ('rider_en_route', models.BooleanField(default=False)),
                ('arriving_soon', models.BooleanField(default=False, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='stores.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1Star', '1Star'), ('2Star', '2Star'), ('3Star', '3Star'), ('4Star', '4Star'), ('5Star', '5Star')], max_length=250)),
                ('comment', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='stores.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('store_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp')),
                ('store_image_url', models.URLField(null=True)),
                ('nin', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/nin')),
                ('nin_url', models.URLField(blank=True)),
                ('cac', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/cac')),
                ('cac_url', models.URLField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.CreateModel(
            name='StoreFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('followed_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_followers', to='stores.store')),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='stores_stor_name_988b60_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['category'], name='stores_stor_categor_a7d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='stores_stor_owner_i_731905_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['store'], name='stores_stat_store_i_47b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['product'], name='stores_stat_product_81637a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('store', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('store', 'user')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store'], name='stores_prod_store_i_c595ef_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['verified'], name='stores_prod_verifie_62d07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='storefollow',
            constraint=models.UniqueConstraint(fields=('follower', 'followed_store'), name='unique_store_follow'),
        ),
    ]
