# Generated by Django 5.2 on 2025-08-16 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.orderdispute'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='orderhistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.order'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='stores.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='stores.product'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='stores.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stores.store'),
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='followed_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_followers', to='stores.store'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='stores_stor_name_988b60_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['category'], name='stores_stor_categor_a7d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='stores_stor_owner_i_731905_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['store'], name='stores_stat_store_i_47b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['product'], name='stores_stat_product_81637a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('store', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('store', 'user')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store'], name='stores_prod_store_i_c595ef_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['verified'], name='stores_prod_verifie_62d07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='storefollow',
            constraint=models.UniqueConstraint(fields=('follower', 'followed_store'), name='unique_store_follow'),
        ),
    ]
