# Generated by Django 5.2 on 2025-08-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='StoreFollow',
        # ),
    ]
