# Generated by Django 5.2 on 2025-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, default='NG', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
