# Generated by Django 5.2 on 2025-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storestatus_image1_alter_storestatus_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Products/Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Products/Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Products/Images/'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Status'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Status'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Status'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Store/Status'),
        ),
    ]
