# Generated by Django 5.2 on 2025-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_order_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='stores.deliveryoption'),
        ),
    ]
