# Generated by Django 5.2 on 2025-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cac',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='nin',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='store/'),
        ),
    ]
