# Generated by Django 5.2 on 2025-08-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_storefollow_follower'),
        ('users', '0016_alter_riderprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefollow',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='users.userprofile'),
        ),
    ]
