# Generated by Django 5.2 on 2025-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_deliveryoption_remove_product_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='name',
            field=models.CharField(choices=[('Movbay_Express', 'Movbay_Express'), ('Speedy_Dispatch', 'Speedy_Dispatch'), ('Pickup', 'Pickup')], max_length=50, unique=True),
        ),
    ]
