# Generated by Django 5.2 on 2025-06-02 18:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_cac_alter_store_nin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-verified']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='stores_prod_name_f67284_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='store',
            name='cac',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/cac'),
        ),
        migrations.AlterField(
            model_name='store',
            name='nin',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/nin'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='store/pp'),
        ),
    ]
