# Generated by Django 5.2 on 2025-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_deliveryoption_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='stores.deliveryoption'),
        ),
    ]
