# Generated by Django 5.2 on 2025-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_product_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('Movbay_Express', 'Movbay_Express'), ('Speedy_Dispatch', 'Speedy_Dispatch'), ('Pickup_Hub', 'Pickup_Hub')], max_length=250, null=True),
        ),
    ]
