# Generated by Django 5.2 on 2025-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_product_delivery_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_types',
        ),
        # migrations.AddField(
        #     model_name='product',
        #     name='free_delivery',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='product',
            name='movbay_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='speed_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='auto_post_to_story',
            field=models.BooleanField(default=False),
        ),
    ]
