# Generated by Django 5.2 on 2025-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_product_delivery_types_product_free_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
