# Generated by Django 5.2 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_product_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='videos'),
        ),
    ]
