# Generated by Django 5.2 on 2025-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_product_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='courier_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shiiping_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
