# Generated by Django 5.2 on 2025-09-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_delivery_courier_name_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(choices=[('movbay_dispatch', 'MovBay Dispatch'), ('speedy_dispatch', 'Speedy Dispatch'), ('pickup_hub', 'Pickup Hub')], max_length=250),
        ),
    ]
