# Generated by Django 5.2 on 2025-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_delivery_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliver_address_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='parcel_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
