# Generated by Django 5.2 on 2025-06-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
