# Generated by Django 5.2 on 2025-09-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_delivery_deliver_address_id_delivery_parcel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='deliver_address_id',
            new_name='delivery_address_id',
        ),
    ]
