# Generated by Django 5.2 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_rename_deliver_address_id_delivery_delivery_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(choices=[('movbay_dispatch', 'MovBay_Dispatch'), ('speedy_dispatch', 'Speedy_Dispatch'), ('pickup_hub', 'Pickup_Hub')], max_length=250),
        ),
    ]
