# Generated by Django 5.2 on 2025-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_delivery_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
