# Generated by Django 5.2 on 2025-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ManyToManyField(to='stores.delivery'),
        ),
    ]
