# Generated by Django 5.2 on 2025-06-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_cart_id_alter_delivery_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreStatus',
            new_name='Status',
        ),
    ]
