# Generated by Django 5.2 on 2025-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_remove_order_delivery_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics_Gadgets', 'Electronics_Gadgets'), ('Fashion_Wears', 'Fashion_Wears'), ('Furniture_Fittings', 'Furniture_Fittings'), ('Health_Beauty', 'Health_Beauty'), ('Hot_Food', 'Hot_Food'), ('Dry_Food_Supplements', 'Dry_Food_Supplements'), ('Groceries', 'Groceries'), ('Sensitive_Items', 'Sensitive_Items'), ('Light_Weight_Items', 'Light_Weight_Items'), ('Machinery', 'Machinery'), ('Medical_Supplies', 'Medical_Supplies')], max_length=250, null=True),
        ),
    ]
