# Generated by Django 5.2 on 2025-06-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_rename_storestatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_url', models.URLField(blank=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.status')),
            ],
        ),
    ]
