# Generated by Django 5.2 on 2025-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='courier_name',
            new_name='courier_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='parcel_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_address_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(choices=[('movbay', 'MovBay'), ('ship_bubble', 'Ship_Bubble'), ('pickup_hub', 'Pickup_Hub')], max_length=250),
        ),
    ]
