# Generated by Django 5.2 on 2025-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_rename_courier_name_delivery_courier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
