# Generated by Django 5.2 on 2025-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_remove_status_image1_remove_status_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
    ]
