# Generated by Django 5.2 on 2025-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_delivery_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='request_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
