# Generated by Django 5.2 on 2025-06-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_status_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusImage',
        ),
    ]
