# Generated by Django 5.2 on 2025-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_delivery_request_token_delivery_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ManyToManyField(related_name='orders', to='stores.delivery'),
        ),
    ]
