# Generated by Django 5.2 on 2025-06-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_delete_statusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['store'], name='stores_stat_store_i_47b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['product'], name='stores_stat_product_81637a_idx'),
        ),
    ]
