# Generated by Django 5.2 on 2025-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_alter_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='followers',
        ),
        migrations.AddField(
            model_name='store',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
