# Generated by Django 5.2 on 2025-06-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_remove_store_followers_store_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
