# Generated by Django 5.2 on 2025-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('New_Orders', 'New_Orders'), ('Processing', 'Processing'), ('Out_for_delivery', 'Out_for_delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=250, null=True),
        ),
    ]
