# Generated by Django 5.2 on 2025-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0031_remove_delivery_store_delivery_alternative_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
