# Generated by Django 5.2 on 2025-06-15 18:13

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_remove_delivery_recipient_name_delivery_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='alternative_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AddField(
            model_name='delivery',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='alternative_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NG'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.delivery', verbose_name='delivery_details'),
        ),
    ]
