# Generated by Django 5.2 on 2025-06-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_profile_storefollow_delete_storefollower_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storefollow',
            name='stores_stor_followe_d37887_idx',
        ),
        migrations.RemoveIndex(
            model_name='storefollow',
            name='stores_stor_followi_bf9f75_idx',
        ),
        migrations.AlterUniqueTogether(
            name='storefollow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='storefollow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='storefollow',
            name='following',
        ),
    ]
