# Generated by Django 5.2 on 2025-06-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_remove_storefollow_stores_stor_followe_d37887_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefollow',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='stores.store'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='storefollow',
            index=models.Index(fields=['follower'], name='stores_stor_followe_d37887_idx'),
        ),
        migrations.AddIndex(
            model_name='storefollow',
            index=models.Index(fields=['following'], name='stores_stor_followi_bf9f75_idx'),
        ),
    ]
