# Generated by Django 5.2 on 2025-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
