# Generated by Django 5.2 on 2025-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0038_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
