# Generated by Django 5.2 on 2025-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0046_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
