# Generated by Django 5.2 on 2025-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0047_remove_product_stock_alter_product_stock_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
