# Generated by Django 5.2 on 2025-07-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0048_alter_product_stock_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
