# Generated by Django 5.2 on 2025-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0049_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
