# Generated by Django 5.2 on 2025-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0050_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
