# Generated by Django 5.2 on 2025-07-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0054_statusimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusImages',
            new_name='StatusImage',
        ),
    ]
