# Generated by Django 5.2 on 2025-07-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0055_rename_statusimages_statusimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statusimages', to='stores.status'),
        ),
    ]
