# Generated by Django 5.2 on 2025-07-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0056_alter_statusimage_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusImage',
        ),
    ]
