# Generated by Django 5.2 on 2025-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0057_delete_statusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
