# Generated by Django 5.2 on 2025-07-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0060_remove_delivery_order_order_deliery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliery',
            new_name='delivery',
        ),
    ]
