# Generated by Django 5.2 on 2025-07-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0065_alter_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
