# Generated by Django 5.2 on 2025-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0067_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New Orders'), ('processing', 'Processing'), ('assigned', 'assigned'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=250),
        ),
    ]
