# Generated by Django 5.2 on 2025-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0068_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
