# Generated by Django 5.2 on 2025-07-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0069_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('arriving_soon', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='stores.order')),
            ],
        ),
    ]
