# Generated by Django 5.2 on 2025-07-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0070_ordertracking'),
        ('users', '0011_riderprofile_created_at_riderprofile_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.riderprofile'),
        ),
    ]
