# Generated by Django 5.2 on 2025-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0075_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
