# Generated by Django 5.2 on 2025-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0076_alter_orderitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='out_for_delivery',
            new_name='item_picked',
        ),
        migrations.RenameField(
            model_name='ordertracking',
            old_name='processing',
            new_name='order_accepted',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='new',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='rider_en_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='arriving_soon',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
