# Generated by Django 5.2 on 2025-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0077_rename_out_for_delivery_ordertracking_item_picked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='marked_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
