# Generated by Django 5.2 on 2025-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0081_order_locked_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New Orders'), ('processing', 'Processing'), ('assigned', 'assigned'), ('ride_accepted', 'ride_accepted'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=250),
        ),
    ]
