# Generated by Django 5.2 on 2025-07-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0082_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cac_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='nin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_image_url',
            field=models.URLField(null=True),
        ),
    ]
