# Generated by Django 5.2 on 2025-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0083_store_cac_url_store_nin_url_store_store_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ride_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New Orders'), ('processing', 'Processing'), ('assigned', 'assigned'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=250),
        ),
    ]
