# Generated by Django 5.2 on 2025-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0084_order_ride_accepted_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
