# Generated by Django 5.2 on 2025-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0085_order_out_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
