# Generated by Django 5.2 on 2025-08-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0086_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
