# Generated by Django 5.2 on 2025-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0087_order_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
